"use client";
import { baselightTheme } from "@/utils/theme/DefaultColors";
import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider } from "@/utils/theme/ThemeContext";
import { SessionProvider } from 'next-auth/react';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const metadata = {
    title: "สหกรณ์ออมทรัพย์กรมทางหลวง จำกัด",
  description: "Generated by Chaimongkon",
  };
  return (
    <html lang="en">
      <title>{metadata.title}</title>
      <body>
        <ThemeProvider>
          <CssBaseline />
          <SessionProvider>{children}</SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
